[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "uvicorn api.main:app --host=0.0.0.0 --port=${PORT:-5000}"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "never"
