POST http://127.0.0.1:8000/api/interpret
Content-Type: application/json

{
  "content":"print(2+2);"
}

###

POST http://127.0.0.1:8000/api/translate
Content-Type: application/json

{
  "content":"print(2+2);"
}

###

POST http://127.0.0.1:8000/api/optimize/eyehole
Content-Type: application/json

{
  "content":"print(2);"
}
